### PR TITLE
add tag property

### PR DESCRIPTION
**Pull request by hosmelq**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Hmm, instead of a tag prop here, maybe it makes more sense to just wrap the children in a fragment, so you can just have your own tag inside.

**Comment by hosmelq** [comment]
`React.Fragment` is supported in react@16.2.0, i think just return `children` can work, what do you think ?

**Comment by sindresorhus** [comment]
If we return `children` it can't be used inside things that requires only one item.

**Comment by hosmelq** [comment]
Yes, you can test it in the sandbox.

**Comment by sindresorhus** [comment]
You're right! It seems they also allow that in v16. I just assumed it didn't work.

**Pull request closed without merging**
