### PR TITLE
Output build as ESM modules

### LINKED ISSUE #13: Use ESM for build
I have been successfully using `react-extras` v0.7.1 for the past year or so. Today, I tried to upgrade to a more recent version but the build failed. Rollup is having trouble importing components from `react-extras` v0.9.0 and later due to the convoluted way that Babel is defining the CommonJS exports.

<details>
    <summary>Click here to see the strack trace from Rollup</summary>

```js
[!] Error: 'Choose' is not exported by node_modules/react-extras/dist/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
lib/components/payment/payment-preview.jsx (3:9)
1: import React, { useEffect, useState } from 'react';
2: import PropTypes from 'prop-types';
3: import { Choose } from 'react-extras';
            ^
4: import { Dimmer, Loader, Message } from 'semantic-ui-react';
5: import { load } from '../../constants';
Error: 'Choose' is not exported by node_modules/react-extras/dist/index.js
    at error (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:5363:30)
    at Module.error (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:9701:9)
    at handleMissingExport (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:9618:21)
    at Module.traceVariable (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:10011:17)
    at ModuleScope.findVariable (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:8678:39)
    at ReturnValueScope.findVariable (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:3054:38)
    at ChildScope.findVariable (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:3054:38)
    at Identifier$1.bind (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:4392:40)
    at CallExpression$1.bind (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:3137:31)
    at CallExpression$1.bind (/Users/sholladay/Code/<redacted>/client/node_modules/rollup/dist/rollup.js:6643:15)
```
</details>

Notably, with v0.9.0, `node_modules/react-extras/dist/index.js` contains:

```js
Object.defineProperty(exports, "Choose", {
  enumerable: true,
  get: function get() {
    return _choose.default;
  }
});
```

Whereas, with previous versions, it was simply:

```js
exports.Choose = Choose;
```

This change was introduced in https://github.com/sindresorhus/react-extras/commit/48b3170d8581dae942841f9c1c7dc9a959c15d8f.

Needless to say, the former is much harder to statically analyze than the latter. We could try to blame Rollup for not being sophisticated enough, but it doesn't surprise me that it is having trouble with this.

I think the best solution would be for `react-extras` to publish a build in ES modules format. That way it's easier for modern bundlers to import.

### PR DESCRIPTION
**Pull request by sholladay**
Fixes #13

This PR updates the build process to produce ES modules instead of CommonJS modules, by removing `@babel/preset-env` and its ESM -> CommonJS transform, which will make it easier for modern ESM-based bundlers (such as [Rollup](https://rollupjs.org/guide/en/)) to import, analyze, and bundle the code, as the exports are statically analyzable. This will also enable [tree-shaking](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80) in modern bundlers, leading to smaller bundle sizes.

Currently, this PR also includes two minor improvements to the build/testing process that are unrelated:
 - Removes the `babel-eslint` custom parser for XO, as it is unnecessary these days.
 - Switches from `prepublishOnly` to `prepare` for the npm script responsible for automatically building the package (see the [docs](https://docs.npmjs.com/cli/publish)). This makes it so the package will be built for local `npm install` during development and also makes it so that the package will be built if installed as a git dependency (something I tend to do a lot when debugging).

### CODE REVIEW

**Comment by sindresorhus** [comment]
I think you need to set `"type": "module"` in package.json.

**Comment by sindresorhus** [comment]
While you're at it, maybe also unbundle https://github.com/sindresorhus/react-extras/blob/master/source/auto-bind.js and https://github.com/sindresorhus/react-extras/blob/master/source/class-names.js CRA2 can handle them as real dependencies.

**Comment by sholladay** [comment]
In unbundled those modules. 👍 

Still need to update the TS definitions. Wasn't really sure what to do there as I haven't re-exported types before. Are we able to just remove them completely and they'll get picked up automatically from the dependency?

**Comment by sindresorhus** [comment]
That’s a good question and I’m not sure. I would explicitly re-export them in the d.ts file just to be sure.

**Comment by sholladay** [comment]
Done. It should work and `tsd` reports no errors.

**Comment by sindresorhus** [comment]
> I think you need to set "type": "module" in package.json.

⬆️

**Comment by sholladay** [comment]
Added the `type` field. Working as expected for me in my project, when installed as a git dependency.

**Pull request merged**
